name: setup-uv-project
description: Install uv and set up the project with its dependencies

runs:
  using: composite
  steps:
    - uses: astral-sh/setup-uv@v6
      with:
        version: ">=0.8.0"
        activate-environment: true
        enable-cache: true
        github-token: ${{ github.token }}

    - shell: bash
      run: uv sync --extra dev
