name: Algorithm Docs Generation

permissions:
  contents: read
  pull-requests: read

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ci-${{ github.repository }}-docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-docs:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: ./.github/actions/setup-uv-project

      - name: Run generation script
        run: python docs/utils/gen_docs.py

      - name: Verify generated files exist
        run: |
          DOCS_DIR="docs/user_manual"

          if [ ! -f "$DOCS_DIR/compression.rst" ]; then
            echo "Error: Expected generated file not found at path: $DOCS_DIR/compression.rst"
            exit 1
          fi

          if [ ! -f "$DOCS_DIR/compatibility_matrix.rst" ]; then
            echo "Error: Expected generated file not found at path: $DOCS_DIR/compatibility_matrix.rst"
            exit 1
          fi

          echo "All required documentation files found in $DOCS_DIR"

      - name: Upload generated files
        uses: actions/upload-artifact@v4
        with:
          name: pruna-docs
          path: |
            docs/user_manual/compression.rst
            docs/user_manual/compatibility_matrix.rst
