name: Algorithm Docs Generation

permissions:
  contents: read
  pull-requests: read

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install dependencies
        run: |
          uv pip install -e .[cpu]

      - name: Remove .so files
        run: find . -name "*.so" -delete

      - name: Run generation script
        run: uv run docs/utils/gen_docs.py

      - name: Verify generated file exists
        run: |
          if [ ! -f compression.rst ]; then
            echo "Error: Generated file 'compression.rst' not found!"
            exit 1
          fi

      - name: Upload generated file
        uses: actions/upload-artifact@v4
        with:
          name: compression-rst
          path: compression.rst
