name: Algorithm Docs Generation

permissions:
  contents: read
  pull-requests: read

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ci-${{ github.repository }}-documentation-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-docs:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: ./.github/actions/setup-uv-project

      - name: Run generation script
        run: python docs/utils/gen_docs.py

      - name: Verify generated file exists
        run: |
          if [ ! -f compression.rst ]; then
            echo "Error: Generated file 'compression.rst' not found!"
            exit 1
          fi

      - name: Upload generated file
        uses: actions/upload-artifact@v4
        with:
          name: compression-rst
          path: compression.rst
