name: Installation Tests

permissions:
  contents: read
  pull-requests: read

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  installation:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry on Windows
        if: runner.os == 'Windows'
        run: |
          powershell -Command "(Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python - --version 1.8.5"
          echo "$(python -m site --user-base)\Scripts" >> $env:GITHUB_PATH

      - name: Install Poetry on Unix
        if: runner.os != 'Windows'
        run: |
          curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.8.5 python3 -
          echo "$(python3 -m site --user-base)/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: pip install -e .
